import { contextBridge, ipcRenderer } from 'electron';

/** Secure bridge: the renderer reaches the main process only through window.dawn. */
const sub = (channel: string, cb: (payload: any) => void) => {
  const listener = (_e: any, payload: any) => cb(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};

const api = {
  runtime: {
    status: () => ipcRenderer.invoke('runtime:status'),
    start: () => ipcRenderer.invoke('runtime:start'),
    stop: () => ipcRenderer.invoke('runtime:stop'),
    restart: () => ipcRenderer.invoke('runtime:restart'),
    switchModel: (path: string) => ipcRenderer.invoke('runtime:switchModel', path),
    logs: () => ipcRenderer.invoke('runtime:logs'),
    onUpdate: (cb: (p: any) => void) => sub('runtime:update', cb),
    onLog: (cb: (p: any) => void) => sub('runtime:log', cb),
  },
  models: {
    cookbook: () => ipcRenderer.invoke('models:cookbook'),
    list: () => ipcRenderer.invoke('model:list'),
    import: () => ipcRenderer.invoke('model:import'),
    select: (p: string) => ipcRenderer.invoke('model:select', p),
    remove: (p: string) => ipcRenderer.invoke('model:remove', p),
    openFolder: () => ipcRenderer.invoke('model:openFolder'),
    systemRam: () => ipcRenderer.invoke('model:systemRam'),
  },
  rag: {
    status: () => ipcRenderer.invoke('rag:status'),
    validate: () => ipcRenderer.invoke('rag:validate'),
    pickFolder: () => ipcRenderer.invoke('rag:pickFolder'),
    estimate: (f: string) => ipcRenderer.invoke('rag:estimate', f),
    addFolder: (f: string) => ipcRenderer.invoke('rag:addFolder', f),
    removeFolder: (f: string) => ipcRenderer.invoke('rag:removeFolder', f),
    index: () => ipcRenderer.invoke('rag:index'),
    pause: () => ipcRenderer.invoke('rag:pause'),
    deleteAll: () => ipcRenderer.invoke('rag:deleteAll'),
    onProgress: (cb: (p: any) => void) => sub('rag:progress', cb),
    retrievalTrace: () => ipcRenderer.invoke('rag:retrievalTrace'),
    rerankerStatus: () => ipcRenderer.invoke('rag:rerankerStatus'),
    evalStatus: () => ipcRenderer.invoke('rag:evalStatus'),
    runEval: () => ipcRenderer.invoke('rag:runEval'),
    reindexInfo: () => ipcRenderer.invoke('rag:reindexInfo'),
    reindexOutdated: () => ipcRenderer.invoke('rag:reindexOutdated'),
  },
  helperRuntime: {
    status: () => ipcRenderer.invoke('helperRuntime:status'),
    start: () => ipcRenderer.invoke('helperRuntime:start'),
    stop: () => ipcRenderer.invoke('helperRuntime:stop'),
    restart: () => ipcRenderer.invoke('helperRuntime:restart'),
    test: () => ipcRenderer.invoke('helperRuntime:test'),
    updateSettings: (patch: any) => ipcRenderer.invoke('helperRuntime:updateSettings', patch),
    pickModel: () => ipcRenderer.invoke('helperRuntime:pickModel'),
    queueStatus: () => ipcRenderer.invoke('helperRuntime:queueStatus'),
    cancelJobs: () => ipcRenderer.invoke('helperRuntime:cancelJobs'),
    clearQueue: () => ipcRenderer.invoke('helperRuntime:clearQueue'),
    analytics: () => ipcRenderer.invoke('helperRuntime:analytics'),
    resetAnalytics: () => ipcRenderer.invoke('helperRuntime:resetAnalytics'),
    exportAnalytics: () => ipcRenderer.invoke('helperRuntime:exportAnalytics'),
    adaptiveStatus: () => ipcRenderer.invoke('helperRuntime:adaptiveStatus'),
    updateAdaptiveRouting: (patch: any) => ipcRenderer.invoke('helperRuntime:updateAdaptiveRouting', patch),
    resetAdaptiveRouting: () => ipcRenderer.invoke('helperRuntime:resetAdaptiveRouting'),
    forceRecoveryProbe: (role: string) => ipcRenderer.invoke('helperRuntime:forceRecoveryProbe', { role }),
  },
  reranker: {
    status: () => ipcRenderer.invoke('reranker:status'),
    start: () => ipcRenderer.invoke('reranker:start'),
    stop: () => ipcRenderer.invoke('reranker:stop'),
    restart: () => ipcRenderer.invoke('reranker:restart'),
    test: () => ipcRenderer.invoke('reranker:test'),
    updateSettings: (patch: any) => ipcRenderer.invoke('reranker:updateSettings', patch),
    pickModel: () => ipcRenderer.invoke('reranker:pickModel'),
    queueStatus: () => ipcRenderer.invoke('reranker:queueStatus'),
    cancelJobs: () => ipcRenderer.invoke('reranker:cancelJobs'),
    clearQueue: () => ipcRenderer.invoke('reranker:clearQueue'),
  },
  setup: {
    complete: (patch: any) => ipcRenderer.invoke('setup:complete', patch),
  },
  hub: {
    catalog: () => ipcRenderer.invoke('hub:catalog'),
    hardware: () => ipcRenderer.invoke('hub:hardware'),
    download: (p: any) => ipcRenderer.invoke('hub:download', p),
    pause: (id: string) => ipcRenderer.invoke('hub:pause', id),
    resume: (id: string) => ipcRenderer.invoke('hub:resume', id),
    cancel: (id: string) => ipcRenderer.invoke('hub:cancel', id),
    downloads: () => ipcRenderer.invoke('hub:downloads'),
    roles: () => ipcRenderer.invoke('hub:roles'),
    setRole: (role: string, path: string) => ipcRenderer.invoke('hub:setRole', { role, path }),
    switchTo: (path: string) => ipcRenderer.invoke('hub:switchTo', path),
    onProgress: (cb: (p: any) => void) => sub('hub:progress', cb),
  },
  optimizer: {
    hardware: (force?: boolean) => ipcRenderer.invoke('optimizer:hardware', force),
    list: () => ipcRenderer.invoke('optimizer:list'),
    analyze: (modelId: string, mode?: string) => ipcRenderer.invoke('optimizer:analyze', { modelId, mode }),
    previewModes: (modelId: string) => ipcRenderer.invoke('optimizer:previewModes', modelId),
    apply: (modelId: string, opts?: any) => ipcRenderer.invoke('optimizer:apply', { modelId, ...(opts || {}) }),
    resetToRecommended: (modelId: string) => ipcRenderer.invoke('optimizer:resetToRecommended', modelId),
    setManualOverride: (modelId: string, override: boolean) => ipcRenderer.invoke('optimizer:setManualOverride', { modelId, override }),
    reoptimizeNeeded: (modelId: string) => ipcRenderer.invoke('optimizer:reoptimizeNeeded', modelId),
    recommendForTask: (task: string) => ipcRenderer.invoke('optimizer:recommendForTask', task),
    name: (id: string) => ipcRenderer.invoke('optimizer:name', id),
    names: (ids: string[]) => ipcRenderer.invoke('optimizer:names', ids),
  },
  research: {
    start: (opts: any) => ipcRenderer.invoke('research:start', opts),
    cancel: (runId: string) => ipcRenderer.invoke('research:cancel', runId),
    pause: (runId: string) => ipcRenderer.invoke('research:pause', runId),
    resume: (runId: string) => ipcRenderer.invoke('research:resume', runId),
    list: () => ipcRenderer.invoke('research:list'),
    get: (runId: string) => ipcRenderer.invoke('research:get', runId),
    report: (runId: string) => ipcRenderer.invoke('research:report', runId),
    delete: (runId: string) => ipcRenderer.invoke('research:delete', runId),
    export: (runId: string, format: 'md' | 'html') => ipcRenderer.invoke('research:export', { runId, format }),
    models: () => ipcRenderer.invoke('research:models'),
    onProgress: (cb: (p: any) => void) => sub('research:progress', cb),
  },
  compare: {
    start: (opts: any) => ipcRenderer.invoke('compare:start', opts),
    cancel: (runId: string) => ipcRenderer.invoke('compare:cancel', runId),
    judge: (runId: string, judgeModel?: string) => ipcRenderer.invoke('compare:judge', { runId, judgeModel }),
    list: () => ipcRenderer.invoke('compare:list'),
    get: (runId: string) => ipcRenderer.invoke('compare:get', runId),
    delete: (runId: string) => ipcRenderer.invoke('compare:delete', runId),
    onProgress: (cb: (p: any) => void) => sub('compare:progress', cb),
  },
  bench: {
    run: (modelPath: string) => ipcRenderer.invoke('bench:run', modelPath),
    history: (modelPath?: string) => ipcRenderer.invoke('bench:history', modelPath),
    best: () => ipcRenderer.invoke('bench:best'),
    delete: (id: string) => ipcRenderer.invoke('bench:delete', id),
    busy: () => ipcRenderer.invoke('bench:busy'),
    onProgress: (cb: (p: any) => void) => sub('bench:progress', cb),
  },
  docs: {
    list: () => ipcRenderer.invoke('docs:list'),
    get: (id: string) => ipcRenderer.invoke('docs:get', id),
    create: (opts?: any) => ipcRenderer.invoke('docs:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('docs:update', { id, patch }),
    remove: (id: string) => ipcRenderer.invoke('docs:remove', id),
    saveVersion: (id: string, label?: string) => ipcRenderer.invoke('docs:saveVersion', { id, label }),
    versions: (id: string) => ipcRenderer.invoke('docs:versions', id),
    restore: (docId: string, versionId: string) => ipcRenderer.invoke('docs:restore', { docId, versionId }),
    ai: (id: string, action: string) => ipcRenderer.invoke('docs:ai', { id, action }),
    export: (id: string, format: string) => ipcRenderer.invoke('docs:export', { id, format }),
    import: () => ipcRenderer.invoke('docs:import'),
  },
  notes: {
    list: (opts?: any) => ipcRenderer.invoke('notes:list', opts),
    get: (id: string) => ipcRenderer.invoke('notes:get', id),
    search: (q: string) => ipcRenderer.invoke('notes:search', q),
    create: (opts?: any) => ipcRenderer.invoke('notes:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('notes:update', { id, patch }),
    remove: (id: string) => ipcRenderer.invoke('notes:remove', id),
    summarize: (id: string) => ipcRenderer.invoke('notes:summarize', id),
    toTask: (id: string) => ipcRenderer.invoke('notes:toTask', id),
    link: (id: string) => ipcRenderer.invoke('notes:link', id),
    unlink: (linkId: string) => ipcRenderer.invoke('notes:unlink', linkId),
  },
  tasks: {
    list: (opts?: any) => ipcRenderer.invoke('tasks:list', opts),
    get: (id: string) => ipcRenderer.invoke('tasks:get', id),
    create: (opts?: any) => ipcRenderer.invoke('tasks:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('tasks:update', { id, patch }),
    remove: (id: string) => ipcRenderer.invoke('tasks:remove', id),
    setStatus: (id: string, status: string) => ipcRenderer.invoke('tasks:setStatus', { id, status }),
    complete: (id: string) => ipcRenderer.invoke('tasks:complete', id),
    askDawn: (id: string) => ipcRenderer.invoke('tasks:askDawn', id),
    overdueCount: () => ipcRenderer.invoke('tasks:overdueCount'),
  },
  cal: {
    list: (start: number, end: number) => ipcRenderer.invoke('cal:list', { start, end }),
    create: (ev: any) => ipcRenderer.invoke('cal:create', ev),
    update: (id: string, patch: any) => ipcRenderer.invoke('cal:update', { id, patch }),
    remove: (id: string) => ipcRenderer.invoke('cal:remove', id),
    exportIcs: (range?: { start: number; end: number }) => ipcRenderer.invoke('cal:exportIcs', range),
    importIcs: () => ipcRenderer.invoke('cal:importIcs'),
  },
  updater: {
    check: () => ipcRenderer.invoke('updater:check'),
    install: () => ipcRenderer.invoke('updater:install'),
    onStatus: (cb: (p: any) => void) => sub('updater:status', cb),
  },
  voice: {
    engine: () => ipcRenderer.invoke('voice:engine'),
    synth: (text: string) => ipcRenderer.invoke('voice:synth', text),
  },
  vault: {
    pick: () => ipcRenderer.invoke('vault:pick'),
    connect: (folder: string) => ipcRenderer.invoke('vault:connect', folder),
    test: () => ipcRenderer.invoke('vault:test'),
    status: () => ipcRenderer.invoke('vault:status'),
    reindex: () => ipcRenderer.invoke('vault:reindex'),
    search: (q: string) => ipcRenderer.invoke('vault:search', q),
    open: () => ipcRenderer.invoke('vault:open'),
    openNote: (rel: string) => ipcRenderer.invoke('vault:openNote', rel),
    writeMemory: (m: any) => ipcRenderer.invoke('vault:writeMemory', m),
    saveConversation: (id: string) => ipcRenderer.invoke('vault:saveConversation', id),
    graphExport: () => ipcRenderer.invoke('vault:graphExport'),
    onProgress: (cb: (p: any) => void) => sub('vault:progress', cb),
  },
  notion: {
    status: () => ipcRenderer.invoke('notion:status'),
    connect: (token: string) => ipcRenderer.invoke('notion:connect', token),
    test: () => ipcRenderer.invoke('notion:test'),
    sync: () => ipcRenderer.invoke('notion:sync'),
    search: (q: string) => ipcRenderer.invoke('notion:search', q),
    open: (url: string) => ipcRenderer.invoke('notion:open', url),
    disconnect: () => ipcRenderer.invoke('notion:disconnect'),
    onProgress: (cb: (p: any) => void) => sub('notion:progress', cb),
  },
  conv: {
    list: () => ipcRenderer.invoke('conv:list'),
    search: (q: string) => ipcRenderer.invoke('conv:search', q),
    get: (id: string) => ipcRenderer.invoke('conv:get', id),
    create: (opts?: any) => ipcRenderer.invoke('conv:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('conv:update', id, patch),
    remove: (id: string) => ipcRenderer.invoke('conv:delete', id),
  },
  chat: {
    send: (p: any) => ipcRenderer.invoke('chat:send', p),
    regenerate: (p: any) => ipcRenderer.invoke('chat:regenerate', p),
    stop: (p: any) => ipcRenderer.invoke('chat:stop', p),
    saveMessageAsNote: (messageId: string) => ipcRenderer.invoke('chat:message:saveAsNote', messageId),
    createTaskFromMessage: (messageId: string) => ipcRenderer.invoke('chat:message:createTask', messageId),
    createDocumentFromMessage: (messageId: string) => ipcRenderer.invoke('chat:message:createDocument', messageId),
    saveMessageAsMemory: (messageId: string) => ipcRenderer.invoke('chat:message:saveAsMemory', messageId),
    linkMessageItem: (messageId: string, targetItemId: string, type?: string) => ipcRenderer.invoke('chat:message:linkItem', { messageId, targetItemId, type }),
    onToken: (cb: (p: any) => void) => sub('chat:token', cb),
    onDone: (cb: (p: any) => void) => sub('chat:done', cb),
    onError: (cb: (p: any) => void) => sub('chat:error', cb),
    onStatus: (cb: (p: any) => void) => sub('chat:status', cb),
    onToolRequest: (cb: (p: any) => void) => sub('chat:tool-request', cb),
    resolveTool: (callId: string, approved: boolean) => ipcRenderer.invoke('chat:tool-resolve', { callId, approved }),
  },
  chatAttachments: {
    addFromClipboard: (conversationId: string, dataUrl: string, name?: string) => ipcRenderer.invoke('chat:attachments:addFromClipboard', { conversationId, dataUrl, name }),
    addFromFile: (conversationId: string) => ipcRenderer.invoke('chat:attachments:addFromFile', { conversationId }),
    removeDraft: (id: string) => ipcRenderer.invoke('chat:attachments:removeDraft', { id }),
    listDraft: (conversationId: string) => ipcRenderer.invoke('chat:attachments:listDraft', { conversationId }),
    listForMessage: (messageId: string) => ipcRenderer.invoke('chat:attachments:listForMessage', { messageId }),
    getPreview: (id: string) => ipcRenderer.invoke('chat:attachments:getPreview', { id }),
    getMetadata: (id: string) => ipcRenderer.invoke('chat:attachments:getMetadata', { id }),
    capabilities: () => ipcRenderer.invoke('vision:capabilities'),
  },
  memory: {
    list: () => ipcRenderer.invoke('memory:list'),
    add: (content: string, type?: string) => ipcRenderer.invoke('memory:add', { content, type }),
    update: (id: string, patch: any) => ipcRenderer.invoke('memory:update', id, patch),
    remove: (id: string) => ipcRenderer.invoke('memory:remove', id),
    clear: () => ipcRenderer.invoke('memory:clear'),
  },
  fileAgent: {
    undo: () => ipcRenderer.invoke('fileagent:undo'),
    openDownloads: () => ipcRenderer.invoke('fileagent:openDownloads'),
    scan: (p: string) => ipcRenderer.invoke('fileagent:scan', p),
  },
  companion: {
    status: () => ipcRenderer.invoke('companion:status'),
    setEnabled: (enabled: boolean) => ipcRenderer.invoke('companion:setEnabled', enabled),
    setPort: (port: number) => ipcRenderer.invoke('companion:setPort', port),
    regeneratePin: () => ipcRenderer.invoke('companion:regeneratePin'),
    firewall: () => ipcRenderer.invoke('companion:firewall'),
  },
  vision: {
    available: () => ipcRenderer.invoke('vision:available'),
    cameras: () => ipcRenderer.invoke('vision:cameras'),
    start: () => ipcRenderer.invoke('vision:start'),
    stop: () => ipcRenderer.invoke('vision:stop'),
    status: () => ipcRenderer.invoke('vision:status'),
    detections: () => ipcRenderer.invoke('vision:detections'),
    context: () => ipcRenderer.invoke('vision:context'),
    ocr: () => ipcRenderer.invoke('vision:ocr'),
    forget: () => ipcRenderer.invoke('vision:forget'),
    snapshot: (annotated?: boolean) => ipcRenderer.invoke('vision:snapshot', annotated),
    frame: () => ipcRenderer.invoke('vision:frame'),
    // Vision Chat model setup (config only — full paths never cross this boundary)
    capabilities: () => ipcRenderer.invoke('vision:capabilities'),
    validate: () => ipcRenderer.invoke('vision:validate'),
    autoDetect: () => ipcRenderer.invoke('vision:autoDetect'),
    applyPair: (modelName: string, mmprojName: string) => ipcRenderer.invoke('vision:applyPair', { modelName, mmprojName }),
    pickModel: (kind: 'model' | 'mmproj') => ipcRenderer.invoke('vision:pickModel', { kind }),
    clearSetup: () => ipcRenderer.invoke('vision:clearSetup'),
    testModel: () => ipcRenderer.invoke('vision:testModel'),
  },
  graph: {
    get: () => ipcRenderer.invoke('graph:get'),
    rebuild: () => ipcRenderer.invoke('graph:rebuild'),
    node: (id: string) => ipcRenderer.invoke('graph:node', id),
  },
  agentos: {
    // runtime manager
    status: () => ipcRenderer.invoke('agentos:status'),
    refresh: () => ipcRenderer.invoke('agentos:refresh'),
    start: () => ipcRenderer.invoke('agentos:start'),
    stop: () => ipcRenderer.invoke('agentos:stop'),
    restart: () => ipcRenderer.invoke('agentos:restart'),
    logs: () => ipcRenderer.invoke('agentos:logs'),
    onStatus: (cb: (p: any) => void) => sub('agentos:status', cb),
    // local knowledge (RAG) collection manager
    collections: () => ipcRenderer.invoke('agentos:collections'),
    sources: (collection: string) => ipcRenderer.invoke('agentos:sources', collection),
    stale: (collection: string) => ipcRenderer.invoke('agentos:stale', collection),
    reindex: (collection: string, path?: string) => ipcRenderer.invoke('agentos:reindex', { collection, path }),
    deleteSource: (collection: string, sourceId: string) => ipcRenderer.invoke('agentos:deleteSource', { collection, sourceId }),
    ingest: (path: string, collection: string) => ipcRenderer.invoke('agentos:ingest', { path, collection }),
    pickFolder: () => ipcRenderer.invoke('agentos:pickFolder'),
    search: (query: string, collection: string, topK?: number) => ipcRenderer.invoke('agentos:search', { query, collection, topK }),
    answer: (query: string, collection: string, topK?: number) => ipcRenderer.invoke('agentos:answer', { query, collection, topK }),
  },
  coding: {
    listWorkspaces: () => ipcRenderer.invoke('coding:listWorkspaces'),
    pickFolder: () => ipcRenderer.invoke('coding:pickFolder'),
    addWorkspace: (folder: string) => ipcRenderer.invoke('coding:addWorkspace', folder),
    updateWorkspace: (id: string, patch: any) => ipcRenderer.invoke('coding:updateWorkspace', { id, patch }),
    removeWorkspace: (id: string) => ipcRenderer.invoke('coding:removeWorkspace', id),
    workspaceInfo: (id: string) => ipcRenderer.invoke('coding:workspaceInfo', id),
    run: (workspaceId: string, task: string, mode?: string) => ipcRenderer.invoke('coding:run', { workspaceId, task, mode }),
    cancel: (workspaceId: string) => ipcRenderer.invoke('coding:cancel', workspaceId),
    status: (workspaceId: string) => ipcRenderer.invoke('coding:status', workspaceId),
    getDiff: (workspaceId: string, runId?: string) => ipcRenderer.invoke('coding:getDiff', { workspaceId, runId }),
    rollback: (workspaceId: string, runId: string) => ipcRenderer.invoke('coding:rollback', { workspaceId, runId }),
    resolveApproval: (id: string, approved: boolean) => ipcRenderer.invoke('coding:resolveApproval', { id, approved }),
    onUpdate: (cb: (p: any) => void) => sub('coding:update', cb),
    onApproval: (cb: (p: any) => void) => sub('coding:approval', cb),
  },
  dcd: {
    available: () => ipcRenderer.invoke('dcd:available'),
    operations: () => ipcRenderer.invoke('dcd:operations'),
    run: (operation: string, params?: any) => ipcRenderer.invoke('dcd:run', { operation, params }),
  },
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    save: (patch: any) => ipcRenderer.invoke('settings:save', patch),
  },
  logs: {
    get: () => ipcRenderer.invoke('logs:get'),
    clear: () => ipcRenderer.invoke('logs:clear'),
    onNew: (cb: (p: any) => void) => sub('log:new', cb),
  },
  security: {
    recent: (limit?: number) => ipcRenderer.invoke('security:recent', limit),
    count: () => ipcRenderer.invoke('security:count'),
    clear: () => ipcRenderer.invoke('security:clear'),
  },
  tools: {
    list: () => ipcRenderer.invoke('tools:list'),
    get: (id: string) => ipcRenderer.invoke('tools:get', id),
    updateEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('tools:updateEnabled', { id, enabled }),
    providers: () => ipcRenderer.invoke('tools:providers'),
    auditRecent: (limit?: number) => ipcRenderer.invoke('tools:auditRecent', limit),
    auditClear: () => ipcRenderer.invoke('tools:auditClear'),
    execute: (toolId: string, input?: any) => ipcRenderer.invoke('tools:execute', { toolId, input }),
    approvalResponse: (id: string, decision: string) => ipcRenderer.invoke('tools:approvalResponse', { id, decision }),
    onApproval: (cb: (req: any) => void) => sub('tools:approval', cb),
  },
  skills: {
    list: () => ipcRenderer.invoke('skills:list'),
    get: (id: string) => ipcRenderer.invoke('skills:get', id),
    create: (opts?: any) => ipcRenderer.invoke('skills:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('skills:update', { id, patch }),
    delete: (id: string) => ipcRenderer.invoke('skills:delete', id),
    test: (id: string, input?: string) => ipcRenderer.invoke('skills:test', { id, input }),
    invokeTool: (id: string, toolId: string, input?: any) => ipcRenderer.invoke('skills:invokeTool', { id, toolId, input }),
    auditRecent: (id?: string, limit?: number) => ipcRenderer.invoke('skills:auditRecent', { id, limit }),
  },
  auth: {
    status: () => ipcRenderer.invoke('auth:status'),
    setPassword: (password: string) => ipcRenderer.invoke('auth:setPassword', password),
    changePassword: (current: string, next: string) => ipcRenderer.invoke('auth:changePassword', { current, next }),
    verifyPassword: (password: string) => ipcRenderer.invoke('auth:verifyPassword', password),
    unlock: (password: string, code?: string) => ipcRenderer.invoke('auth:unlock', { password, code }),
    lock: () => ipcRenderer.invoke('auth:lock'),
    setSecuritySetting: (key: string, value: any, password?: string) => ipcRenderer.invoke('auth:setSecuritySetting', { key, value, password }),
    setupTotp: () => ipcRenderer.invoke('auth:setupTotp'),
    confirmTotp: (code: string) => ipcRenderer.invoke('auth:confirmTotp', code),
    disableTotp: (password: string) => ipcRenderer.invoke('auth:disableTotp', password),
    regenerateBackupCodes: (password: string) => ipcRenderer.invoke('auth:regenerateBackupCodes', password),
    backupRemaining: () => ipcRenderer.invoke('auth:backupRemaining'),
    audit: (limit?: number) => ipcRenderer.invoke('auth:audit', limit),
    lanStatus: () => ipcRenderer.invoke('auth:lanStatus'),
    onLock: (cb: () => void) => sub('auth:locked', cb),
  },
  secrets: {
    health: () => ipcRenderer.invoke('vault:health'),
    list: () => ipcRenderer.invoke('vault:list'),
    create: (opts: any) => ipcRenderer.invoke('vault:create', opts),
    update: (id: string, patch: any) => ipcRenderer.invoke('vault:update', { id, patch }),
    delete: (id: string) => ipcRenderer.invoke('vault:delete', id),
    reveal: (id: string, password?: string) => ipcRenderer.invoke('vault:reveal', { id, password }),
    rotateMasterKey: () => ipcRenderer.invoke('vault:rotateMasterKey'),
  },
  email: {
    presets: () => ipcRenderer.invoke('email:presets'),
    providerGuides: () => ipcRenderer.invoke('email:providerGuides'),
    testIncoming: (cfg: any) => ipcRenderer.invoke('email:testIncoming', cfg),
    testOutgoing: (cfg: any) => ipcRenderer.invoke('email:testOutgoing', cfg),
    listAccounts: () => ipcRenderer.invoke('email:listAccounts'),
    getAccount: (id: string) => ipcRenderer.invoke('email:getAccount', id),
    createAccount: (cfg: any) => ipcRenderer.invoke('email:createAccount', cfg),
    updateAccount: (id: string, patch: any) => ipcRenderer.invoke('email:updateAccount', { id, patch }),
    deleteAccount: (id: string, deleteCredential?: boolean) => ipcRenderer.invoke('email:deleteAccount', { id, deleteCredential }),
    testConnection: (cfg: any) => ipcRenderer.invoke('email:testConnection', cfg),
    listFolders: (accountId: string) => ipcRenderer.invoke('email:listFolders', accountId),
    sync: (accountId: string, folder?: string) => ipcRenderer.invoke('email:sync', { accountId, folder }),
    listMessages: (accountId: string, folder?: string, opts?: any) => ipcRenderer.invoke('email:listMessages', { accountId, folder, opts }),
    getMessage: (id: string) => ipcRenderer.invoke('email:getMessage', id),
    thread: (threadKey: string) => ipcRenderer.invoke('email:thread', threadKey),
    summarize: (id: string) => ipcRenderer.invoke('email:summarize', id),
    summarizeThread: (threadKey: string) => ipcRenderer.invoke('email:summarizeThread', threadKey),
    extractActions: (id: string) => ipcRenderer.invoke('email:extractActions', id),
    draftReply: (id: string, instruction?: string) => ipcRenderer.invoke('email:draftReply', { id, instruction }),
    saveDraft: (draft: any) => ipcRenderer.invoke('email:saveDraft', draft),
    getDraft: (id: string) => ipcRenderer.invoke('email:getDraft', id),
    deleteDraft: (id: string) => ipcRenderer.invoke('email:deleteDraft', id),
    send: (draftId: string) => ipcRenderer.invoke('email:send', draftId),
    attachmentInfo: (id: string) => ipcRenderer.invoke('email:attachmentInfo', id),
    downloadAttachment: (id: string) => ipcRenderer.invoke('email:downloadAttachment', id),
    tags: () => ipcRenderer.invoke('email:tags'),
    createTag: (name: string, color?: string) => ipcRenderer.invoke('email:createTag', { name, color }),
    tagMessage: (messageId: string, tagId: string) => ipcRenderer.invoke('email:tagMessage', { messageId, tagId }),
    untagMessage: (messageId: string, tagId: string) => ipcRenderer.invoke('email:untagMessage', { messageId, tagId }),
    createTask: (id: string) => ipcRenderer.invoke('email:createTask', id),
    createCalendar: (id: string) => ipcRenderer.invoke('email:createCalendar', id),
    saveNote: (id: string) => ipcRenderer.invoke('email:saveNote', id),
    audit: (limit?: number) => ipcRenderer.invoke('email:audit', limit),
  },
  backup: {
    create: (opts?: any) => ipcRenderer.invoke('backup:create', opts),
    estimateSize: (opts?: any) => ipcRenderer.invoke('backup:estimateSize', opts),
    verify: (p: string) => ipcRenderer.invoke('backup:verify', p),
    details: (p: string) => ipcRenderer.invoke('backup:details', p),
    history: () => ipcRenderer.invoke('backup:history'),
    openFolder: () => ipcRenderer.invoke('backup:openFolder'),
    deleteSafetySnapshot: (id: string) => ipcRenderer.invoke('backup:deleteSafetySnapshot', id),
    chooseDestination: () => ipcRenderer.invoke('backup:chooseDestination'),
    chooseArchive: () => ipcRenderer.invoke('backup:chooseArchive'),
    restore: (path: string, password?: string) => ipcRenderer.invoke('backup:restore', { path, password }),
    onRestored: (cb: () => void) => sub('backup:restored', cb),
  },
  maturity: {
    list: () => ipcRenderer.invoke('maturity:list'),
    check: () => ipcRenderer.invoke('maturity:check'),
    get: (id: string) => ipcRenderer.invoke('maturity:get', id),
  },
  search: {
    query: (term: string) => ipcRenderer.invoke('search:query', term),
  },
  workspace: {
    listItems: (opts?: any) => ipcRenderer.invoke('workspace:items:list', opts),
    getItem: (id: string) => ipcRenderer.invoke('workspace:items:get', id),
    createItem: (input: any) => ipcRenderer.invoke('workspace:items:create', input),
    updateItem: (id: string, patch: any) => ipcRenderer.invoke('workspace:items:update', { id, patch }),
    deleteItem: (id: string) => ipcRenderer.invoke('workspace:items:delete', id),
    listLinks: (itemId: string) => ipcRenderer.invoke('workspace:links:list', itemId),
    createLink: (input: any) => ipcRenderer.invoke('workspace:links:create', input),
    deleteLink: (id: string) => ipcRenderer.invoke('workspace:links:delete', id),
    related: (itemId: string) => ipcRenderer.invoke('workspace:related:get', itemId),
    search: (q: any) => ipcRenderer.invoke('workspace:search', q),
    convertToTask: (itemId: string) => ipcRenderer.invoke('workspace:convertToTask', itemId),
    saveAsNote: (input: any) => ipcRenderer.invoke('workspace:saveAsNote', input),
    reconcile: () => ipcRenderer.invoke('workspace:reconcile'),
    coverage: () => ipcRenderer.invoke('workspace:coverage'),
  },
  diagnostics: {
    bundle: () => ipcRenderer.invoke('diagnostics:bundle'),
    summary: () => ipcRenderer.invoke('diagnostics:summary'),
    export: () => ipcRenderer.invoke('diagnostics:export'),
  },
  openExternal: (url: string) => ipcRenderer.invoke('open:external', url),
  onNav: (cb: (view: string) => void) => sub('nav', cb),
};

contextBridge.exposeInMainWorld('dawn', api);
export type DawnApi = typeof api;
